### ISSUE TITLE
Support integration with sbt-projectmatrix

### ISSUE THREAD

**Issue by jeffmay** [djspiewak/sbt-github-actions#118]
Although this project has a lot of great customization options, it does not really play well with [sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix).

The primary obstacle is the fact that the generated workflow assumes that all subprojects will be compatible with the same Scala version. The workflow assumes that you can use the `++` sbt operator in order to force a Scala version on all subprojects. There is no way to remove this. There is also no way to remove the scala version from the github workflow matrix as doing so results in a `NoSuchElementException` when the plugin attempts to call `.head` on the list of Scala versions.

The easiest solution would be to make it possible simplify the workflow a bit so that `sbt-projectmatrix` can do what it is good at and generate all of the subprojects and run all of the builds and tests with the versions specified (and remove the use of `++` and the scala version matrix at the top-level).

Alternatively, if we wanted better integration with github's matrix support, then we could have some way to opt-in to using projectmatrix instead of crossScalaVersions to generate the workflow and actually use the subproject configurations to generate the github workflow matrix. This is obviously a more challenging task, but it would make a much better experience for viewing the results in Github.

**Comment by jeffmay** [comment]
Oddly, the [documentation of SBT](https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Switching+Scala+version) suggests the `++` will only apply the scala version to the projects that list that version in their `crossScalaVersions` setting, however, when I run it on my project [scalacheck-ops](https://github.com/rallyhealth/scalacheck-ops/pull/62), it appears to run on all projects, regardless of what the settings are for `crossScalaVersions`.

**Comment by jeffmay** [comment]
Here is an example of a [custom workflow in scalacheck-ops](https://github.com/rallyhealth/scalacheck-ops/pull/63) that lets `sbt-projectmatrix` handle the Scala versions itself.

**Comment by armanbilge** [comment]
Have a look at sbt-typelevel-github-actions, specifically the `githubWorkflowBuildSbtStepPreamble` setting.

> The workflow assumes that you can use the `++` sbt operator in order to force a Scala version on all subprojects. There is no way to remove this.

This is precisely what `githubWorkflowBuildSbtStepPreamble` lets you do: adjust the pre-amble of every sbt step.

https://typelevel.org/sbt-typelevel/gha.html

**Comment by jeffmay** [comment]
> Have a look at sbt-typelevel-github-actions, specifically the `githubWorkflowBuildSbtStepPreamble` setting.
> 
> > The workflow assumes that you can use the `++` sbt operator in order to force a Scala version on all subprojects. There is no way to remove this.
> 
> This is precisely what `githubWorkflowBuildSbtStepPreamble` lets you do: adjust the pre-amble of every sbt step.
> 
> https://typelevel.org/sbt-typelevel/gha.html

So I was able to remove the `++` from the build job, however, I cannot remove it from the publish job. See [https://github.com/rallyhealth/scalacheck-ops/pull/62/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR195]

I even tried some publish build options:
https://github.com/rallyhealth/scalacheck-ops/pull/62/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R48-R51

Any chance we can add a `githubWorkflowPublishSbtStepPreamble` setting key?

**Comment by jeffmay** [comment]
Moved this conversation to https://github.com/typelevel/sbt-typelevel/issues/391
