### ISSUE TITLE
Does clean.yml really work?

### ISSUE THREAD

**Issue by ldeluigi** [djspiewak/sbt-github-actions#21]
If it's supposed to delete artifacts from previous actions, why am I still able to download them or delete them?

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/93199574-d9b13300-f74e-11ea-860d-091cad81948b.png)

**Comment by djspiewak** [comment]
It's a bit of a race condition. If you go back to older jobs, you shouldn't be able to see any artifacts. Only the most recent job is likely to have them, since clean often runs before those artifacts are published.

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/93230305-d1b9b900-f777-11ea-9dd4-177f560f2c2d.png)

I picked a random old job, I'm still seeing them 😞

**Comment by djspiewak** [comment]
Interesting. I wonder if they changed their API. I'll look into it.

**Comment by ldeluigi** [comment]
The problem could be that $1 is empty.

You can retrieve the repo _owner/name_ from the context `${{ github.repository }}` and pass as the first argument ([doc](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)).

And btw you don't need to hard-code github api location because it's stored inside the GITHUB_API_URL variable ([doc](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)).

**Comment by ldeluigi** [comment]
Ok I confirm I managed to fix the script. I'll do a PR.
