### ISSUE TITLE
clean.yml could have become unnecessary

### ISSUE THREAD

**Issue by ldeluigi** [djspiewak/sbt-github-actions#35]
I found this setting under Actions:

![image](https://user-images.githubusercontent.com/44567586/99161395-2fc03980-26f2-11eb-8c5f-f5d26f4199e8.png)

**Comment by djspiewak** [comment]
Hmm, can it be set to 0? Part of the problem here is the fact that build artifacts in this workflow are used to pass data between jobs, so they're entirely ephemeral and should *never* be retained.

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/99183151-2490fc00-273a-11eb-9475-28466d233139.png)

Sadly no.


Meanwhile, Travis CI has changed their policy and now basically forces you to pay money so I'm expecting a progressively migration to many big projects to GitHub Actions: I hope this new influx of users will make GitHub pay more attention to current issues and needs.

**Comment by djspiewak** [comment]
> Meanwhile, Travis CI has changed their policy and now basically forces you to pay money so I'm expecting a progressive migration of many big projects to GitHub Actions: I hope this new influx of users will make GitHub pay more attention to current issues and needs.

Yeah I'm experiencing exactly this as well. I had already migrated to gha, but TravisCI has definitely been a serious forcing function in a lot of other ecosystems, such as Typelevel.
