### ISSUE TITLE
Add safe setEnv/prependPath workflow steps

### ISSUE THREAD

**Issue by dcsobral** [djspiewak/sbt-github-actions#37]
Setting an environment variable and prepending to `PATH` is now done through temporary files, whose names are provided through the environment variables `GITHUB_ENV` and `GITHUB_PATH`. Specialized workflow steps for these action would be very convenient.

**Comment by djspiewak** [comment]
There are actually already specialized workflow steps for these, but they use the old `set-env` trick. They need to be updated to use the new one now that the old has been disabled.

**Comment by dcsobral** [comment]
Oh? I missed that.

Consider this a bug, then. :)

I'll PR it.

-- 
Daniel C. Sobral

**Comment by djspiewak** [comment]
> I'll PR it.

Actually I already have it done locally. Should be released soon.

**Comment by djspiewak** [comment]
Fixed in 0.9.5
