### ISSUE TITLE
Optional automerge action for scala-steward PRs

### ISSUE THREAD

**Issue by joroKr21** [djspiewak/sbt-github-actions#39]
Would there be interest in adding an optional automerge action for scala-steward?
 - Could use for example https://github.com/marketplace/actions/merge-me
 - There is also Mergify but idk if it can run as a GitHub action

**Comment by djspiewak** [comment]
It's definitely doable, I'm just not sure it belongs here. Doesn't mergify meet the criteria? I haven't actually played with it too much.

**Comment by joroKr21** [comment]
I'm not sure either. But it's definitely something that a lot of Scala libraries could benefit from and save some precious maintainer time. Depends on the goals of this plugin.

**Comment by joroKr21** [comment]
@djspiewak how do you regenerate the test files?

**Comment by nafg** [comment]
One issue I see with mergify is that apparently you have to specify every matrix permutation like this:

https://github.com/http4s/http4s/blob/main/.mergify.yml

Since the job name includes the minor scala version, this means the mergify file will get invalidated quite often.

Is there a way to make the job names less specific?

**Comment by joroKr21** [comment]
I opened a PR with https://github.com/marketplace/actions/merge-me which is a GitHub action unlike Mergify

**Comment by djspiewak** [comment]
Is it possible to use wildcards in the matrix definition? I see some above in the labels.

**Comment by joroKr21** [comment]
This is happening in typelevel/sbt-typelevel#190

**Comment by joroKr21** [comment]
I think sbt-typelevel solves the issue you mentioned about the matrix

**Comment by nafg** [comment]
As does my library
