### ISSUE TITLE
Consider `main` as default branch name (instead of `master`)

### ISSUE THREAD

**Issue by gabrielmagno** [djspiewak/sbt-github-actions#41]
Since [October 2020](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), the default branch for new repositories is `main` (instead of `master`).

It would be good for `sbt-github-actions` to consider this new behaviour. Not sure if it would be better to _replace_ the current behaviour (make `main` as default) or to _add_ main as a new valid branch name (both `main` and `master` will be the default).

**Comment by djspiewak** [comment]
IMO we should just replace `master` as the default primary branch. I haven't gotten around to implementing this (it's relatively trivial), but it's worth doing.

**Comment by froth** [comment]
I think this can be closed, as you already did it :) https://github.com/djspiewak/sbt-github-actions/commit/6dba544bc3b4f93a537343855597a332067c2975 

Thanks for doing so! And also thanks for this great project. I had to migrate from travis-ci and it was a delight :)
