### ISSUE TITLE
Auto add scalafmtCheckAll when .scalafmt.conf is present

### ISSUE THREAD

**Issue by lewisjkl** [djspiewak/sbt-github-actions#49]
Maybe this is out of scope for this library, but I have noticed myself adding `WorkflowStep.Sbt(List("scalafmtCheckAll"), name = Some("Check Formatting"))` on any projects I have added this plugin to. If this is out of scope, no worries. But if not then I am happy to put up a PR for this!

**Comment by djspiewak** [comment]
I'm definitely a little leery of doing something quite like this, since scalafmt is often folded into `ci` aliases in projects which use this plugin (though your approach is also not uncommon). I think it's better to leave it up to the downstream user rather than trying to be *too* magical! :-)
