### ISSUE TITLE
Failed to compress for modules that weren't compiled

### ISSUE THREAD

**Issue by lewisjkl** [djspiewak/sbt-github-actions#50]
Working on adding this plugin in https://github.com/cb372/scalacache/pull/470 and I had to actually add an extra workflow step:

```
WorkflowStep.Sbt(List("benchmarks/compile"), name = Some("Compile Benchmarks"))
```

because the `benchmarks` were not being compiled at all or run in the CI pipeline. This means that no `target/` directory was created for `benchmarks` and so the `tar` in the Compression step of the pipeline was failing out.

Not sure if it is really feasible to fix this situation or not. But I thought I would at least post an issue here for there to be a record of my workaround when encountering this.

**Comment by djspiewak** [comment]
This is a common issue unfortunately. :-( I wasn't able to find a nice solution to it other than `githubWorkflowArtifactUpload`. Basically, if you add `githubWorkflowArtifactUpload := false` to every *project* that doesn't produce a `target` directory when compiled from root, it resolves the issue. So in this case, `benchmarks / githubWorkflowArtifactUpload` would be `false`.

**Comment by lewisjkl** [comment]
Perfect, thanks for the suggestion! And also thanks for making this library, it is super nice to have!
