### ISSUE TITLE
OverlappingFileLockException

### ISSUE THREAD

**Issue by tomasherman** [djspiewak/sbt-github-actions#59]
Hello, im getting OverlappingFileLockException when using CI generated by this plugin. It seems this is happening when SBT compiler bridge is being compiled. Not sure what to do about it :( It's happening pretty consistently. Any ideas what can be done about that pls? :)

**Comment by tomasherman** [comment]
it seems like `-Dsbt.boot.lock=false` helps, probably not a bulletproof solution though

**Comment by djspiewak** [comment]
Fascinating! Are you using self-hosted runners? I'm not sure how a containerized runner could experience this issue.
