### ISSUE TITLE
Adding githubWorkflowBuildPostamble

### ISSUE THREAD

**Issue by MPV** [djspiewak/sbt-github-actions#6]
What's your thoughts on adding a `githubWorkflowBuildPostamble`?
(compared to existing `githubWorkflowBuildPreamble`)

I imagine it could be used for things like annotating from jUnit test reports:
https://github.com/marketplace/actions/junit-report-to-annotations

For example, in `build.sbt`:
```sbt
ThisBuild / githubWorkflowBuildPostamble := Seq(
  WorkflowStep.Use(
    "ashley-taylor",
    "junit-report-annotations-action",
    "v1.0",
    name = Some(s"jUnit report"),
    cond = Some(s"always()"),
    params = Map(
      "access-token" -> "${{ secrets.GITHUB_TOKEN }}"
    )
  )
)
```

**Comment by djspiewak** [comment]
Sounds like a good idea to me! Right now you would need to do this by manually post-processing the generated workflow, which is a very blunt instrument.
