### ISSUE TITLE
Autogenerated .yml files don't have newline at end of file

### ISSUE THREAD

**Issue by mdedetrich** [djspiewak/sbt-github-actions#69]
Any files that are generated by the `githubWorkflowGenerate` don't have a newline at the end of the file. Its recommended to have newlines at the end of any source files to help with compatibility issues between *nix and Windows.

I noticed this when creating a PR that github complains about missing newlines at the end of the file.

**Comment by djspiewak** [comment]
Should be a very straightforward thing to fix!
