### ISSUE TITLE
githubWorkflowUseSbtThinClient should default to false due to current issues

### ISSUE THREAD

**Issue by mdedetrich** [djspiewak/sbt-github-actions#74]
This is more of a suggestion but it seems like a lot of people are having problems with sbt's thin client mode (see https://github.com/sbt/sbt/issues/6468). An issue I just found is that currently when SBT runs with `--client` it ignores all environment variables which makes the `env` field for `WorkflowStep.Sbt` not even work (you can see the PR at https://github.com/iheartradio/ficus/pull/155 where I had to set this to `false` because sbt-coveralls cannot even pick up the env vars)

My suggestion would be to set it completely to `false` until the problems with a new SBT release.

**Comment by armanbilge** [comment]
+1. See https://github.com/typelevel/cats/pull/3952 and https://github.com/http4s/http4s/pull/4938#issuecomment-881753861.

**Comment by mdedetrich** [comment]
@djspiewak Shall I close the issue or do you want me to leave it open?

**Comment by armanbilge** [comment]
@mdedetrich pretty sure this will be addressed, lots of projects are making this change including https://github.com/typelevel/cats-effect/pull/2150#issuecomment-889864381.

**Comment by djspiewak** [comment]
Ah, didn't realize it wasn't linked. This is fixed in main and will be released soon

**Comment by mdedetrich** [comment]
@yanns I think you are right, just made a PR for it here https://github.com/djspiewak/sbt-github-actions/pull/101
