### ISSUE TITLE
Define a build matrix also in publish step

### ISSUE THREAD

**Issue by nicolasfara** [djspiewak/sbt-github-actions#83]
Could be grate if you would give the configuration for an execution matrix also for the publish step of the CI.
In my particular case i've to build 3 different jar for each OS (win, linux and mac) and publish them to github artifacts, since with the current config I can't do that.

**Comment by djspiewak** [comment]
That's really interesting. In general it's a really bad idea to do this though because your releases become non-atomic, so you can have partially-released stuff. Can you build the JARs in the `build` job and carry them through in the artifacts to `publish`?

**Comment by nicolasfara** [comment]
My question raise on the need to publish a JavaFX application directly from the CI. Since JavaFX is redistributed with different dependencies for each OS, I thought that was a good idea to publish a different jar for each Os. Seaching on the web and discuss the problem with my colleagues, we ended up to take all the Jars (for all os) and put them into the Jar. Now we have a single Jar that runs on all platforms. In this case we no need a publish step with multiple os and your explanation make sense: i close the issue, thanks so much!
