### ISSUE TITLE
switch to setup-java action (to replace setup-scala which is no longer maintained)

### ISSUE THREAD

**Issue by pjfanning** [djspiewak/sbt-github-actions#89]
I initially raised this because Eclipse Temurium has taken over Adoptium - https://adoptium.net/

I then discovered that setup-scala doesn't support Temurin and is no longer being maintained - https://github.com/olafurpg/setup-scala/issues/49

**Comment by djspiewak** [comment]
Agreed. This is a yak I need to shave sooner rather than later.
