### ISSUE TITLE
Upload artifact fails if target directory doesn't exist

### ISSUE THREAD

**Issue by mpilquist** [djspiewak/sbt-github-actions#9]
Ran in to this on fs2, where the build action runs `test` in certain sub-projects only. Hence, some subprojects don't have a `target` directory and the upload fails.

https://github.com/functional-streams-for-scala/fs2/actions/runs/137190325

**Comment by djspiewak** [comment]
Unfortunately, there's no way in general for this plugin to tell what target directories will or will not get generated, and there are no file existence predicates [available in GitHub Actions](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions). However, you *can* achieve this in the following way: https://github.com/djspiewak/sbt-github-actions/blob/3c40ebb75d0e3f170cb4e72417ef59effa12ef27/src/sbt-test/sbtghactions/non-existent-target/build.sbt#L10-L19

It's a little annoying, but it works and you really only have to do it once.
